const $=id=>document.getElementById(id);const {simulate,valueAt}=FilterSimulation;
let windowSeconds=60;
let data,now=windowSeconds,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,lastFrame=0;
function parameters(){return {dt:+$('dt').value,tau:+$('tau').value,freq:+$('freq').value,late:+$('late').value,timing:$('timingMode').value,wave:$('wave').value,buffer:$('buffer').value};}
function rebuild(){const p=parameters();data=simulate(p);
$('latenessLabel').textContent=p.timing==='fixed'?'Lateness every execution':'Maximum task lateness';
$('latenessHint').textContent=p.timing==='fixed'?`Every execution is exactly ${p.late} ms late relative to its scheduled release. With overdue releases skipped, executions are ${(Math.floor(p.late/p.dt)+1)*p.dt} ms apart. Delays below dt shift execution time without skipping releases.`:'Each wake-up is delayed by 0–this many milliseconds, using repeatable random jitter.';
const signalInfo={
stress:['Pattern frequency','Full-scale +1/−1 reversals with unequal hold times: 30%, 20%, 35%, and 15% of each pattern. At 0.01 Hz these last 30, 20, 35, and 15 seconds.'],
noisy:['Input frequency','A sine trend with uniform sample noise up to ±0.35. The same source samples are used for both filters.'],
drift:['Drift rate','Smooth, random changes in level with sample noise up to ±0.20. Rate sets how often a new drift target is reached.'],
spikes:['Spike rate','A slowly varying baseline with narrow positive or negative spikes at irregular positions within each period, plus noise.'],
steps:['Level-change rate','Random levels that change once per period, with sample noise up to ±0.15.'],
mixed:['Base frequency','Three tones at 1×, 2.7× and 7.1× the base frequency, with amplitudes 0.5, 0.3 and 0.2.'],
sine:['Input frequency','A pure sine wave for a clean reference.'],
square:['Input frequency','A repeating jump between −1 and +1.']};
$('frequencyLabel').textContent=signalInfo[p.wave][0];$('waveHint').textContent=signalInfo[p.wave][1]+(['noisy','drift','spikes','steps'].includes(p.wave)?' Noise and events repeat exactly when you change task jitter.':'')+(p.wave==='mixed'&&7.1*p.freq>=500/p.dt?' Some tones exceed half the source sample rate and will alias.':'');$('dtOut').textContent=p.dt+' ms';$('lateOut').textContent=p.late+' ms';$('tauOut').textContent=p.tau.toFixed(1)+' s';$('freqOut').textContent=p.freq.toFixed(2)+' Hz';$('coefficient').textContent=`τ = ${p.tau.toFixed(1)} s · analog cutoff ≈ ${(1/(2*Math.PI*p.tau)).toFixed(4)} Hz · dt = ${p.dt} ms · source rate = ${(1000/p.dt).toFixed(1)} Hz · α = ${data.alpha.toFixed(6)}`;
$('stressExplanation').textContent=p.wave==='stress'?'Why this exposes timing error: sustained levels give the on-time filter time to respond, while skipped updates make the late filter much slower. Set lateness to 0 to make the traces match, or process all buffered samples to reduce the error. This is a severe scheduling scenario, not a claim that all jitter causes large errors.':'';
$('bufferHint').textContent=p.buffer==='queue'?'Every source sample advances the filter once. Results appear in batches when the task runs.':'Older unread samples are overwritten. The fixed coefficient is applied once per task execution.';
$('code').textContent=`// Initialization: tau and dt are in seconds\nconst float tau = ${p.tau.toFixed(1)}f;\nconst float dt = ${(p.dt/1000).toFixed(3)}f; // fixed\nconst float alpha = dt / (tau + dt);\nfloat y = 0;\n\n// Whenever the scheduled task actually runs\n${p.buffer==='queue'?'while (queue_has_sample()) {\n    x = pop_oldest_sample();\n    y += alpha * (x - y);\n}\npublish(y);':'x = read_latest_sample();\ny += alpha * (x - y);\npublish(y);'}`;
$('interpretation').textContent=p.buffer==='queue'?'With a lossless queue, the filter computes the same sequence of values as the on-time filter. Wall-clock output still holds and jumps because results are published late.':'With a latest-value mailbox, long delays skip source samples and reduce the number of filter updates per second. The output can lag more and change shape. Jitter has no single effective cutoff frequency.';draw();}
function context(id){const canvas=$(id),r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);c.font='12px ui-monospace, monospace';return {c,w:r.width,h:r.height};}
function draw(){if(!data)return;let {c,w,h}=context('plot');const left=42,right=w-12,top=16,bottom=h-28,start=now-windowSeconds;const X=t=>left+(t-start)/windowSeconds*(right-left),Y=v=>top+(1.25-v)/2.5*(bottom-top);
c.strokeStyle='#293448';c.fillStyle='#a5b1c4';c.lineWidth=1;for(const v of [-1,-.5,0,.5,1]){c.beginPath();c.moveTo(left,Y(v));c.lineTo(right,Y(v));c.stroke();c.textAlign='right';c.fillText(v.toFixed(1),left-9,Y(v)+4);}for(let tick=windowSeconds===60?10:windowSeconds===15?3:1,i=Math.ceil(start/tick)*tick;i<=now;i+=tick){c.beginPath();c.moveTo(X(i),top);c.lineTo(X(i),bottom);c.stroke();c.textAlign='center';c.fillText(i.toFixed(0)+'s',X(i),h-5);}
c.save();c.beginPath();c.rect(left,top,right-left,bottom-top);c.clip();
function trace(events,color,width){c.strokeStyle=color;c.lineWidth=width;c.beginPath();let y=valueAt(events,start);c.moveTo(left,Y(y));for(const e of events){if(e.t<=start)continue;if(e.t>now)break;c.lineTo(X(e.t),Y(y));c.lineTo(X(e.t),Y(e.y));y=e.y;}c.lineTo(right,Y(y));c.stroke();}
trace(data.source,'#75829a',1.3);trace(data.ideal,'#5be3ce',2);trace(data.late,'#ffac70',2.2);c.restore();
({c,w,h}=context('timing'));const t0=now-1,l=77,r=w-12,xt=t=>l+(t-t0)*(r-l);c.textAlign='left';c.fillStyle='#a5b1c4';c.fillText('Source',0,29);c.fillText('Task',0,63);for(const row of [25,59]){c.strokeStyle='#293448';c.beginPath();c.moveTo(l,row);c.lineTo(r,row);c.stroke();}for(const [events,color,row] of [[data.source,'#5be3ce',25],[data.late,'#ffac70',59]]){c.strokeStyle=color;c.lineWidth=2;for(const e of events){if(e.t<t0)continue;if(e.t>now)break;c.beginPath();c.moveTo(xt(e.t),row-7);c.lineTo(xt(e.t),row+7);c.stroke();}}c.fillStyle='#a5b1c4';c.font='12px ui-monospace,monospace';c.fillText('−1 s',l,94);c.textAlign='right';c.fillText('now',r,94);
let error=0,referenceEnergy=0,previous=start;const times=[start,...data.ideal.filter(e=>e.t>start&&e.t<now).map(e=>e.t),...data.late.filter(e=>e.t>start&&e.t<now).map(e=>e.t),now].sort((a,b)=>a-b);for(const t of times){const mid=(previous+t)/2,d=valueAt(data.ideal,mid)-valueAt(data.late,mid);error+=d*d*(t-previous);referenceEnergy+=valueAt(data.ideal,mid)**2*(t-previous);previous=t;}
$('rms').textContent=Math.sqrt(error/windowSeconds).toFixed(3);$('relativeRms').textContent=referenceEnergy>1e-12?(100*Math.sqrt(error/referenceEnergy)).toFixed(1)+'% of on-time output RMS':'Reference output is zero';const events=data.late.filter(e=>e.t>start&&e.t<=now);$('interval').textContent=events.length>1?((events.at(-1).t-events[0].t)/(events.length-1)*1000).toFixed(1):'—';const count=events.reduce((s,e)=>s+e.consumed,0),skips=events.reduce((s,e)=>s+e.skipped,0);$('skipped').textContent=count?(skips/count*100).toFixed(1):'0.0';}
function playState(){ $('pause').textContent=playing?'Pause':'Resume';$('pause').setAttribute('aria-pressed',String(!playing));$('status').textContent=playing?'RUNNING':'PAUSED';}
$('stressPreset').onclick=()=>{for(const [id,value] of Object.entries({dt:20,tau:6,freq:.01,late:200,timingMode:'random',wave:'stress',buffer:'latest',window:60}))$(id).value=String(value);windowSeconds=60;now=60;rebuild();};
$('pause').onclick=()=>{playing=!playing;playState();};for(const id of ['dt','late','timingMode','tau','freq','wave','buffer'])$(id).addEventListener('input',rebuild);$('window').addEventListener('change',()=>{windowSeconds=+$('window').value;now=Math.max(now,windowSeconds);draw();});window.addEventListener('resize',draw);rebuild();playState();
function frame(t){if(playing){now+=Math.min((t-lastFrame)/1000||0,.1);if(now>180)now=windowSeconds;draw();}lastFrame=t;requestAnimationFrame(frame);}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_filter_timing',description:'Set scheduler lateness, optionally choose random or fixed timing, and choose newest-sample or buffered processing.',inputSchema:{type:'object',properties:{timing:{type:'string',enum:['random','fixed']},latenessMs:{type:'number',minimum:0,maximum:200},buffer:{type:'string',enum:['latest','queue']}},required:['latenessMs','buffer'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||!Number.isFinite(input.latenessMs)||input.latenessMs<0||input.latenessMs>200||!['latest','queue'].includes(input.buffer)||(input.timing!==undefined&&!['random','fixed'].includes(input.timing)))throw new Error('Valid lateness 0–200 ms and buffer latest or queue required');$('late').value=String(Math.round(input.latenessMs));$('buffer').value=input.buffer;if(input.timing!==undefined)$('timingMode').value=input.timing;rebuild();return parameters();}})).catch(()=>{});}catch{}}
